dist: trusty
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "12"
  - "10"
  - "8"
script:
  - yarn
  - yarn lint
  - yarn test:coveralls
cache:
  yarn: true
  directories:
    - "node_modules"
