# dist: trusty
matrix:
  include:
    - dist: bionic
      node_js:
        - "node"
        - "lts/*"
        - "12"
        - "10"
        - "8"
    - dist: xenial
      node_js:
        - "node"
        - "lts/*"
        - "12"
        - "10"
        - "8"
    - dist: trusty
      node_js:
        - "node"
        - "lts/*"
        - "12"
        - "10"
        - "8"
    # - dist: precise
language: node_js
script:
  - yarn
  - yarn lint
  - yarn test:coveralls
cache:
  yarn: true
  directories:
    - node_modules
    - buildcache