# dist: trusty
matrix:
  include:
    - os: linux
      dist: bionic
      node_js: "node"
    - os: linux
      arch: arm64
      dist: bionic
    - os: linux
      dist: xenial
      node_js: "node"
    - os: linux
      dist: trusty
      node_js: "node"
    - os: linux
      dist: bionic
      node_js: "lts/*"
    - os: linux
      dist: xenial
      node_js: "lts/*"
    - os: linux
      dist: trusty
      node_js: "lts/*"
    - os: windows
      node_js: "node"
    - os: "osx"
      node_js: "node"
language: node_js
script:
  - yarn
  - yarn lint
  - yarn test:coveralls
cache:
  yarn: true
  directories:
    - node_modules
    - buildcache