# dist: trusty
matrix:
  include:
    # - dist: bionic
    # - dist: xenial
    - dist: trusty
    - dist: precise
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "12"
  - "10"
script:
  - yarn
  - yarn lint
  - yarn test:coveralls
cache:
  yarn: true
  directories:
    - node_modules
    - buildcache