# dist: trusty
matrix:
  include:
    - os: linux
      dist: bionic
      node_js: node
    - os: linux
      arch: arm64
      dist: bionic
      node_js: node
    - os: linux
      dist: bionic
      node_js: 12
    - os: linux
      dist: bionic
      arch: arm64
      node_js: 12
    - os: linux
      dist: bionic
      node_js: 10
    - os: linux
      dist: bionic
      arch: arm64
      node_js: 10
    - os: linux
      dist: xenial
      node_js: node
    - os: linux
      arch: arm64
      dist: xenial
      node_js: node
    - os: linux
      dist: xenial
      node_js: 12
    - os: linux
      arch: arm64
      dist: xenial
      node_js: 12
    - os: linux
      dist: xenial
      node_js: 10
    - os: linux
      arch: arm64
      dist: xenial
      node_js: 10
    - os: linux
      dist: trusty
      node_js: node
    - os: linux
      dist: trusty
      node_js: 12
    - os: linux
      dist: trusty
      node_js: 10
    # - os: windows
    #   node_js: node
    # - os: windows
    #   node_js: 12
    # - os: windows
    #   node_js: 10
    - os: osx
      node_js: node
    - os: osx
      node_js: 12
    - os: osx
      node_js: 10
language: node_js
script:
  - yarn
  - yarn lint
  - yarn test:coveralls
cache:
  yarn: true
  directories:
    - node_modules
    - buildcache