name: Build and test

continue-on-error: true
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - 'master'
      - 'test'
      - 'create-workflow/*'
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-16.04
          - windows-2019
          - windows-2016
        node-version: 
          - 13.x
          - 12.x
          - 10.x 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: setup node ${{matrix.node-version}}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{matrix.node-version}}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2.1.6
        id: tsbuild-cache 
        with:
          path: buildcache.tsbuildinfo
          key: ${{ runner.os }}-tsbuild
          restore-keys: |
            ${{ runner.os }}-tsbuild
      - uses: actions/cache@v2.1.6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install packages
        run:  yarn install
      - name: check linting
        run: yarn lint
      - name: test
        run: yarn test
