name: Build and test

on:
  push:
    branches:
      - master
      - create-workflow
      - create-workflow/*
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-16.04
          - windows-2019
          - windows-2016
        node-version: 
          - 8.x
          - 10.x
          - 12.x
          - 13.x
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup node ${{matrix.node-version}}
        uses: actions/setup-node@v1.4.1
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run:  yarn install
      - name: check linting
        run: yarn lint
      - name: test
        run: yarn test
